KTH/kpm

- app.js
Add version (from evolene version file) to `_monitor` output.  Will be "unknown" in local development, but the correct information for an actual build.
Q: Should we use a global `const version` to avoid loading the `./buildinfo.js` on each request?  Or do we have more than enough global consts as it is?  Maybe a node `require` has good enough caching anyway?
> Add version info to _monitor.

- client/kpm.js
- client/menu.css
- client/translation.js
- package-lock.json
- package.json
This is my proposal for how we should handle internationalization in KPM on the client side. It's basically a function that returns and object with the translations.
```js
const translations = {
en: {
loading: "Loading",
menu: "Menu",
login: "Log in",
},
sv: {
loading: "Laddar",
menu: "Meny",
login: "Logga in",
},
};
/**
*
* @param {string} input input you want to translate
* @param {string} lang language you want to translate into
* @returns {string}
*/
function intl(input, lang) {
return translations[lang][input];
}
module.exports = intl;
```
The idea is to connect this to a cookie so that the lang param is always whatever you've chosen and set as your language by means of cookie. The next iteration would probably be replacing lang with a request to cookies. 
I think this works for …
> Internationalization

- client/kpm.js
- client/menu.css
- server/panels/router.js
Get the kpm base url from the relevant `script` tag instead of trying to evaluate a runtime environment variable in parcel.
There is still a problem with importing `menu.css`.  I have arranged things so that the menu works, but there is still an ugly stack trace in the console.   There is also a bunch of `consle.log("kpm: ...")` added. Most of them (if not all) should probably be removed later, but for now, until we get our fist 500 or so users, there's no harm in keeping them.
> Don't use env in kpm.js

- app.js
- server/server.js
- server/utils.js
<details>
<summary>Benchmarks</summary>
Test: 1000 connections (100 concurrent) towards KPM deployed locally
```
$ ab -n 1000 -c 100 http://localdev.kth.se:3000/kpm
50%   4753
66%   6217
75%  21815
80%  23063
90%  24254
95%  30507
98%  84960
99%  87397
100%  100676 (longest request)
```
```
$ ab -n 1000 -c 100 http://localdev.kth.se:3000/kpm
50%    119
66%    130
75%    134
80%    138
90%    150
95%    156
98%    173
99%    174
100%    174 (longest request)
```
</details>
> Implement a in-memory cache for Cortina blocks

- .env.in
- package-lock.json
- package.json
- server/openid/extract-info.js
- server/panels/router.js
Load course name (in swedish and english) from kopps, with redis caching.
To do before merging:
> Load course names

- kpm/kpm-backend/.env.in
- kpm/kpm-backend/src/api.ts
KPM backend should have and use a canvas authentication token for calling my-canvas-rooms-api.
> Canvas auth in kpm.

- kpm/kpm-backend-interface/src/index.ts
- kpm/kpm-backend/.env.in
- kpm/kpm-backend/package-lock.json
- kpm/kpm-backend/package.json
- kpm/kpm-backend/src/api.ts
- kpm/kpm-frontend/src/panes/i18n.ts
- kpm/kpm-frontend/src/panes/teaching.scss
- kpm/kpm-frontend/src/panes/teaching.tsx
- kpm/kpm-frontend/src/stylesVars.scss
- package-lock.json
- package.json
Main review question: Does the changes in the `APITeaching` type look reasonable.
Todo:
> Make kpm-backend teaching response more complete.

- apis/my-studies-api/__test__/convertToCoursesProgrammes.spec.ts
- apis/my-studies-api/src/api.ts
- apis/my-studies-api/src/apiUtils.ts
- kpm/kpm-backend-interface/src/index.ts
- kpm/kpm-backend/src/api.ts
- kpm/kpm-frontend/src/panes/studies.tsx
- kpm/kpm-frontend/src/panes/teaching.tsx
* Changed api return structure in my-studies-api
* Changed api return structure for studies in kpm-backend to resemble the teaching structure (mention each course once).
* Document some endpoint return types with the generic parameter of `express.Response<T>`.
> Structured course data for studies.

- kpm/kpm-backend-interface/src/index.ts
- kpm/kpm-backend/.env.in
- kpm/kpm-backend/src/api.ts
New required settings in kpm-backend:
```sh
SOCIAL_USER_URI=https://www.kth.se/social/user
SOCIAL_KEY=
```
> Implement kpm-backend wrapper for groups.

- kpm/kpm-frontend/src/app.scss
- kpm/kpm-frontend/src/components/menu.scss
- packages/kpm-ug-rest-client/src/ugRestClient.ts
This PR fixes the `inset` (top, bottom, left, right) CSS properties so that KPM does not cover the full page
(Note: this PR might include more small CSS fixes)
> Fix kpm so it doesn't cover the full page

- kpm/kpm-frontend/src/app.tsx
- kpm/kpm-frontend/src/components/links.tsx
This PR fixes two issues when using hash routing on a page. There are two use case:
- anchor links within a page
- tab navigation in Canvas (which uses hash routing)
We achieve this by:
- showing menu bar regardless of what hash we currently are on
- going back to previous hash route when closing the menu
> Fix routing when on a page with a hash route

- kpm/kpm-backend-interface/src/index.ts
- kpm/kpm-backend/src/index.ts
- packages/kpm-api-common/src/errors.ts
- packages/kpm-api-common/src/index.ts
[403 Forbidden](https://en.wikipedia.org/wiki/HTTP_403)
The request contained valid data and was understood by the server, but the server is refusing action. This may be due to the user not having the necessary permissions for a resource or needing an account of some sort, or attempting a prohibited action (e.g. creating a duplicate record where only one is allowed). This code is also typically used if the request provided authentication by answering the WWW-Authenticate header field challenge, but the server did not accept that authentication. The request should not be repeated.
I added "CorsError" as possible error name because it is such a specific kind of error of high magnitude.
> Mute CORS errors and make sure they send the correct statusCode

- kpm/kpm-backend/src/api/common.ts
- kpm/kpm-backend/src/api/commonCache.ts
We could improve error handling in the actual resolver that causes the error, but this is the general error handler and will do for now.
> Package and decorate error in memoizer for better general error logging

- kpm/kpm-backend/src/api/teaching.ts
A teacher asked what magic order the courses are sorted by, noting it was impossible to figure out. As it turns out, we had random order. Changing this to order by course code. This should improve discovery when browsing the list.
> Sort courses in teaching alphabetically by course code (for now)

- kpm/kpm-backend/src/auth.ts
Single values of memberOf are returned as a string from login server but we expect an array.
> Single values of memberOf

- kpm/kpm-backend/src/api/common.ts
- kpm/kpm-backend/src/api/groups.ts
- kpm/kpm-backend/src/api/programmes.ts
- kpm/kpm-backend/src/api/services.ts
- kpm/kpm-backend/src/session.ts
- kpm/kpm-frontend/src/panes/services.tsx
- kpm/kpm-frontend/src/panes/utils.ts
Set accept-language on all backend requests in frontent, and propagate that header to any requests to social in the backend.
This fixes the translations for service links.
> Use accept-language.

- kpm/kpm-frontend/src/Menu.scss
- kpm/kpm-frontend/src/_vars.scss
- kpm/kpm-frontend/src/components/groups.scss
- kpm/kpm-frontend/src/components/menu.scss
Use the `$data-something-svg` variables provided by kth-style rather than trying to load icons externally from the kth-style app.
This gets rid of the CSP error where we try to load ref urls in prod.
kmp-frontend already had a dependency to kth-style, so I only needed to use it.
> Use data urls for svg icons.

- kpm/kpm-backend/src/api/useBeta.ts
Before we change to opt-out, there must be a way of opting out.
This can be released to prod at any time.
> Set `use_kpm` to `f` when deactivating.

- .proxyrc
- kpm/kpm-backend/src/widget.js.ts
- kpm/kpm-frontend/src/components/groups.scss
- kpm/kpm-frontend/src/components/groupsUtils.ts
This solves an issue where teachers with small laptop screens couldn't see the full Cours Admin dropdown menu.
> Dropdown menu size fix

- kpm/kpm-backend/src/auth.ts
We now get givenname in login claims which allows us to show correct name in menu.
This solves KTH-INC-4307639
> We now get givenname in login claims

- kpm/kpm-frontend/src/index.tsx
- kpm/kpm-frontend/src/state/authState.ts
TODO: Discuss session length since KPM-session is 14 days and SSO is a lot shorter which could mean that other sites are logged out.
With multiple tabs refreshing, we will not trigger the kpmLoaded unless the tab is visible to avoid lots of redirects to the login form.
> Trigger kpmLoaded-event after session has been checked

- kpm/kpm-frontend/src/panes/services.scss
The main selected services list is two columns, not a bunch of rows, so "Annual ..." comes below "Administrate", not beside.  Also a bunch of cleanup of the main layout of the services panel (less calc, fewer properties, let the flex handling in the browser do the math).
https://trello.com/c/n0GW8mHA
> Sort services in columns.

- kpm/kpm-frontend/src/Menu.scss
Mainly needed at intra.kth.se, but also improves contrast as any text or images scrolls below the menu bar.
Requested in [KTH-INC-4308367](https://edge.sys.kth.se/itsm/EfecteFrameset.do#/workspace/datacard/view/173558211).
> Add white bottom border to menu bar.

- kpm/kpm-frontend/src/stylesCanvas.scss
Canvas appear to have changed how menus are positioned so this has no effect, it does cause issues with overlays (such as accessability checker). Removing this. KTH-INC-4389439-Canvasfel
> Not needed for menus, conflicts with overlay info boxes

- kpm/kpm-backend/src/api/studies.ts
Consider a course "current" from 14 (not just 5) dsys before the first tuition date.
> Make course current earlier.

- kpm/kpm-frontend/src/components/menuUtils.ts
The previous version got some floating point accuracy issues which caused flicker.
> Use actual content height when calculating overflow mode

- kpm/kpm-frontend/src/Menu.scss
Validators and Pär Landberg complained about mismatching types for some uses of the `--kpmPad` css variable.  Add a default of 1em (which is a sane if large default, but should never actually be used, as the variable have a global value).
> Make validators happy

- kpm/kpm-backend/src/widget.js/notLoggedIn.js
- kpm/kpm-frontend/src/components/entrances.tsx
This PR changes the way kpm guesses which is the current "site" (external, student-web or intranet).
Instead of looking at the URL, it looks if a given class is present in the header.
> Read current site without using RegEx

- kpm/kpm-backend/src/index.ts
- kpm/kpm-frontend/__test__/__snapshots__/test-panesGroups.spec.tsx.snap
- kpm/kpm-frontend/__test__/__snapshots__/test-panesProfile.spec.tsx.snap
- kpm/kpm-frontend/__test__/__snapshots__/test-panesServices.spec.tsx.snap
- kpm/kpm-frontend/src/Menu.tsx
- kpm/kpm-frontend/src/panes/groups.tsx
- kpm/kpm-frontend/src/panes/profile.tsx
- kpm/kpm-frontend/src/panes/programme.tsx
- kpm/kpm-frontend/src/panes/services.tsx
- kpm/kpm-frontend/src/panes/studies.tsx
- kpm/kpm-frontend/src/panes/teaching.tsx
- kpm/kpm-frontend/src/panes/utils.ts
This PR generalizes the function `getMainHost` defined in `utils.ts` https://github.com/KTH/kpm/pull/228/files#diff-250f66c7f2d531bf7e4d12ee34da020d24a51afbff2765307ce229247197b29b and applies in all places where URLs are created
> Add support for "stage" URLs

- kpm/kpm-frontend/__test__/__snapshots__/test.spec.tsx.snap
- kpm/kpm-frontend/src/Menu.scss
- kpm/kpm-frontend/src/Menu.tsx
This PR fixes these accessibility problems:
- The button to open the personal menu in mobile was not focusable.
`<a>` tags without `href` are not focusable. This PR replaces the element with `<button>`
- The links for personal menu (Studies, Teaching...) were focusable even when they were not visible
The links were "non-visible" by making the container shorter than the content, which meant that buttons were still focusable. This PR adds `display: none` to the container
> Fix: accessible mobile menu

- kpm/kpm-frontend/src/app.scss
- kpm/kpm-frontend/src/components/groupsUtils.ts
This PR fixes the following problem:
- There is a React hook `useDropdownPosition` that calculates the position of a dropdown
- That hook sets more inline styles (visibility, opacity) which conflicts with CSS classes that controls visibility. Inline styles also have higher specificity than CSS
_There are other problems related with the dropdown, but those can be solved in upcoming PRs_
> Bug in dropdown: visible even when not intended

- kpm/kpm-backend/src/api/studies.ts
With this PR, UG groups that don't have a "omgångsnummer" (1 digit) or "kurstillfälleskod" (5 digits) are _not_ considered "course rounds", which can be problematic for courses that spans multiple terms. Hypothetical example:
The course "DD.1320" is held in terms "20212", "20221" and "20222" (3 terms). In this case, the student is a member of the following groups:
- `ladok.courses.DD.1320.registredade_20212.1` (has `.1` in the end, it is the course round)
- `ladok.courses.DD.1320.registrerade_20212`
- `ladok.courses.DD.1320.registrerade_20221`
- `ladok.courses.DD.1320.registrerade_20222`
The first group is the actual course round the student is registered. The other 3 do not represent any course round, there is no Canvas course room for them and should _not_ be considered by KPM as …
> Ignore roles without round code
