KTH/kpm

- .env.in
- package-lock.json
- package.json
- src/index.handlebars
- src/kpm-loggedin.js.handlebars
- src/middleware/authenticationMiddleware.js
- src/server.js
I've got a few todos that I want to look into before I call this a proper PR but until then please check out and comment on my session handling middleware
> Implemented a session handler

- client/toggle-menu.js
- package-lock.json
- server/cookie-router.js
- server/server.js
- server/utils.js
> Cookie options

- packages/my-canvas-rooms-api/Dockerfile
- packages/my-canvas-rooms-api/__test__/test.spec.ts
- packages/my-canvas-rooms-api/src/api.ts
- packages/my-canvas-rooms-api/src/canvasApi.ts
- packages/my-teaching-api/Dockerfile
- packages/my-teaching-api/src/index.ts
Add useful meta data to link objects.
> Feature decorate rooms

- kpm/kpm-frontend/.proxyrc
- kpm/kpm-frontend/__test__/__snapshots__/test.spec.tsx.snap
- kpm/kpm-frontend/jest.config.js
- kpm/kpm-frontend/package-lock.json
- kpm/kpm-frontend/package.json
- kpm/kpm-frontend/src/Menu.tsx
- kpm/kpm-frontend/src/app.tsx
- kpm/kpm-frontend/src/components/menu.tsx
- kpm/kpm-frontend/src/components/placeholder.tsx
- kpm/kpm-frontend/src/components/utils.tsx
- kpm/kpm-frontend/src/panes/groups.tsx
- kpm/kpm-frontend/src/panes/profile.tsx
- kpm/kpm-frontend/src/panes/programme.tsx
- kpm/kpm-frontend/src/panes/schedule.tsx
- kpm/kpm-frontend/src/panes/services.tsx
- kpm/kpm-frontend/src/panes/studies.tsx
- kpm/kpm-frontend/src/panes/teaching.tsx
- kpm/kpm-frontend/src/routes.tsx
- kpm/kpm-frontend/src/styles.scss
- package-lock.json
Related to https://github.com/KTH/kpm/pull/38
> Feature router without animated menus

- apis/my-canvas-rooms-api/.env.in
- apis/my-canvas-rooms-api/evolene-local-packages.json
- apis/my-canvas-rooms-api/package-lock.json
- apis/my-canvas-rooms-api/package.json
- apis/my-canvas-rooms-api/src/config.ts
- apis/my-studies-api/.env.in
- apis/my-studies-api/evolene-local-packages.json
- apis/my-studies-api/package-lock.json
- apis/my-studies-api/package.json
- apis/my-studies-api/src/api.ts
- apis/my-studies-api/src/config.ts
- apis/my-teaching-api/.env.in
- apis/my-teaching-api/evolene-local-packages.json
- apis/my-teaching-api/package-lock.json
- apis/my-teaching-api/package.json
- apis/my-teaching-api/src/api.ts
- apis/my-teaching-api/src/config.ts
- kpm/kpm-backend/evolene-local-packages.json
- kpm/kpm-backend/package-lock.json
- kpm/kpm-backend/package.json
- kpm/kpm-backend/src/config.ts
- package-lock.json
- package.json
- packages/@types-kth__reqvars/index.d.ts
- packages/@types-kth__reqvars/package-lock.json
- packages/@types-kth__reqvars/package.json
- packages/evolene-local-packages/package-lock.json
- packages/kpm-api-common/package-lock.json
Remove asserts from code and enforce env vars by .env.in file spec. This allows tests to be run without setting CLIENT_ID and CLIENT_SECRET.
> Use @kth/reqvars to enforce (added shared types package)

- apis/my-teaching-api/__test__/callDummyUser.spec.ts
- apis/my-teaching-api/src/api.ts
Not ready to merge yet, see review comments.
> Make my-teaching-api return roles per course.

- kpm/kpm-backend/src/api.ts
Put the getting of course rooms in a common function, since it is to be used by multiple endpoints.  Also, that function may be a good place to implement caching of canvas rooms.
> Minor refactor in kpm-backend

- kpm/kpm-frontend/src/app.scss
- kpm/kpm-frontend/src/components/groups.scss
- kpm/kpm-frontend/src/components/groups.tsx
- kpm/kpm-frontend/src/components/menu.scss
- kpm/kpm-frontend/src/panes/studies.tsx
- kpm/kpm-frontend/src/panes/teaching.scss
- kpm/kpm-frontend/src/panes/teaching.tsx
- kpm/kpm-frontend/src/stylesReset.scss
- kpm/kpm-frontend/src/stylesVars.scss
This is an implementation of the new design.
Includes a very lightweight dropdown that respects available size built on \<details\> element.
> New teaching UI

- kpm/kpm-backend/.env.in
- kpm/kpm-backend/src/api.ts
- kpm/kpm-backend/src/auth.ts
- kpm/kpm-frontend/src/components/common.scss
- kpm/kpm-frontend/src/components/common.tsx
- kpm/kpm-frontend/src/components/menu.scss
- kpm/kpm-frontend/src/panes/profile.tsx
- kpm/kpm-frontend/src/panes/studies.tsx
- kpm/kpm-frontend/src/panes/teaching.tsx
- kpm/kpm-frontend/src/panes/utils.ts
- kpm/kpm-frontend/src/routes.tsx
- kpm/kpm-frontend/src/stylesVars.scss
New loading behaviour. Now we open the menu and show spinner inline whilst waiting for data.
> Refactor loading

- kpm/kpm-backend-interface/src/index.ts
- kpm/kpm-frontend/src/i18n/en.ts
- kpm/kpm-frontend/src/i18n/sv.ts
- kpm/kpm-frontend/src/panes/studies.scss
- kpm/kpm-frontend/src/panes/studies.tsx
- kpm/kpm-frontend/src/panes/teaching.tsx
- kpm/kpm-frontend/src/panes/utils.ts
TODO: Which room and role should be shown?
TODO: Create proper links to PM and registration
NOTE: Examination rooms from Canvas currently not shown
> Show courses in studies

- kpm/kpm-backend-interface/src/index.ts
- kpm/kpm-backend/src/api/common.ts
- kpm/kpm-backend/src/api/index.ts
- kpm/kpm-backend/src/api/star.ts
- kpm/kpm-frontend/src/components/common.scss
- kpm/kpm-frontend/src/components/common.tsx
- kpm/kpm-frontend/src/components/icons.tsx
- kpm/kpm-frontend/src/panes/groups.scss
- kpm/kpm-frontend/src/panes/groups.tsx
- kpm/kpm-frontend/src/panes/programme.scss
- kpm/kpm-frontend/src/panes/programme.tsx
- kpm/kpm-frontend/src/panes/services.tsx
> Handle star toggling.

- apis/my-studies-api/.env.in
- apis/my-studies-api/src/api.ts
- apis/my-studies-api/src/index.ts
- apis/my-studies-api/src/publicApi.ts
- apis/my-teaching-api/.env.in
- apis/my-teaching-api/src/api.ts
- apis/my-teaching-api/src/index.ts
- apis/my-teaching-api/src/publicApi.ts
- kpm/kpm-backend/.env.in
- kpm/kpm-backend/src/api/studies.ts
- kpm/kpm-backend/src/api/teaching.ts
This PR adds authorization logic between KPM backend and my-xxx-apis.
- Declare env variables for access tokens
- Protect my-xxx-api behind a token
- Send authorization tokens from kpm to my-xxx-api
> Protect APIs

- kpm/kpm-frontend/src/Menu.tsx
- kpm/kpm-frontend/src/app.scss
- kpm/kpm-frontend/src/stylesCanvas.scss
Fixes to KPM Menu in Canvas
Set --kpm-bar-height in a Reactified way
> Canvas css fixes

- apis/my-teaching-api/src/api.ts
- kpm/kpm-frontend/src/panes/teaching.scss
- kpm/kpm-frontend/src/panes/teaching.tsx
Fixed some styling bugs and showing exam rooms
> Improve teaching

- kpm/kpm-backend-interface/src/index.ts
- kpm/kpm-backend/src/activation.ts
- kpm/kpm-backend/src/api/common.ts
- kpm/kpm-backend/src/api/studies.ts
- kpm/kpm-backend/src/auth.ts
- kpm/kpm-backend/src/index.ts
- kpm/kpm-backend/src/session.ts
- kpm/kpm-backend/src/widget.js.ts
- kpm/kpm-frontend/src/Menu.tsx
- kpm/kpm-frontend/src/app.scss
- kpm/kpm-frontend/src/app.tsx
- kpm/kpm-frontend/src/components/common.scss
- kpm/kpm-frontend/src/components/common.tsx
- kpm/kpm-frontend/src/components/courseComponents.tsx
- kpm/kpm-frontend/src/components/login.scss
- kpm/kpm-frontend/src/components/login.tsx
- kpm/kpm-frontend/src/components/menu.tsx
- kpm/kpm-frontend/src/components/utils.tsx
- kpm/kpm-frontend/src/panes/groups.tsx
- kpm/kpm-frontend/src/panes/profile.tsx
- kpm/kpm-frontend/src/panes/programme.tsx
- kpm/kpm-frontend/src/panes/services.scss
- kpm/kpm-frontend/src/panes/services.tsx
- kpm/kpm-frontend/src/panes/studies.tsx
- kpm/kpm-frontend/src/panes/teaching.tsx
- kpm/kpm-frontend/src/panes/utils.ts
- kpm/kpm-frontend/src/state/PubSub.ts
- kpm/kpm-frontend/src/state/authState.ts
> Login on auth expire

- kpm/kpm-backend-interface/src/index.ts
- kpm/kpm-backend/src/api/studies.ts
- kpm/kpm-backend/src/api/teaching.ts
- kpm/kpm-frontend/__test__/__snapshots__/test-panesGroups.spec.tsx.snap
- kpm/kpm-frontend/__test__/__snapshots__/test-panesProfile.spec.tsx.snap
- kpm/kpm-frontend/__test__/__snapshots__/test-panesServices.spec.tsx.snap
- kpm/kpm-frontend/src/components/courseComponents.tsx
- kpm/kpm-frontend/src/i18n/en.ts
- kpm/kpm-frontend/src/i18n/sv.ts
- kpm/kpm-frontend/src/panes/studies.scss
- kpm/kpm-frontend/src/panes/studies.tsx
- kpm/kpm-frontend/src/panes/teaching.tsx
Frontend finish for teaching pane and studies pane
> Fix teaching studies

- kpm/kpm-backend-interface/src/index.ts
- kpm/kpm-backend/src/auth.ts
- kpm/kpm-frontend/src/Menu.tsx
- kpm/kpm-frontend/src/app.tsx
- kpm/kpm-frontend/src/components/utils.tsx
- kpm/kpm-frontend/src/panes/utils.ts
- kpm/kpm-frontend/src/routes.tsx
- kpm/kpm-frontend/src/state/authState.ts
We are checking each group that the user belongs to to determine if the menu items should be shown:
studies: curr.startsWith("ladok2.kurser")
programmes: curr.startsWith("ladok2.program")
teaching: curr.startsWith("edu.courses")
> Hide Studies / Teaching if empty

- kpm/kpm-frontend/__test__/__snapshots__/test-panesGroups.spec.tsx.snap
- kpm/kpm-frontend/src/app.scss
- kpm/kpm-frontend/src/components/filter.scss
- kpm/kpm-frontend/src/components/filter.tsx
- kpm/kpm-frontend/src/components/icons.scss
- kpm/kpm-frontend/src/components/icons.tsx
- kpm/kpm-frontend/src/components/menu.scss
- kpm/kpm-frontend/src/panes/groups.scss
- kpm/kpm-frontend/src/panes/programme.scss
- kpm/kpm-frontend/src/panes/studies.scss
- kpm/kpm-frontend/src/panes/teaching.scss
- kpm/kpm-frontend/src/stylesVars.scss
Feedback from KTH Style implemented
- changing some paddings
- fixed filter
- removed non-standard lines
> KTH Style Adaptions

- apis/my-canvas-rooms-api/src/api.ts
- apis/my-canvas-rooms-api/src/canvasApi.ts
Fixar https://trello.com/c/zrTula7p
> If a user is not found in canvas, that is not an error.

- kpm/kpm-backend/src/auth.ts
- kpm/kpm-frontend/src/i18n/en.ts
- kpm/kpm-frontend/src/i18n/sv.ts
And log the occurrence for troubleshooting
> Don't throw error if memberOf isn't an Array

- kpm/kpm-frontend/src/app.scss
- kpm/kpm-frontend/src/components/groups.tsx
- kpm/kpm-frontend/src/components/groupsUtils.ts
More robust dropdown behaviour and can handle switching between desktop/mobile when open.
> Fix dropdown timing

- apis/my-canvas-rooms-api/src/api.ts
- apis/my-canvas-rooms-api/src/canvasApi.ts
- apis/my-canvas-rooms-api/src/interface.ts
Is this a good way handle errors that should not be status 500 (and does not need to be logged as error) ?
> Improve error handling in my-canvas-rooms-api.

- kpm/kpm-backend-interface/src/index.ts
- kpm/kpm-backend/src/auth.ts
- kpm/kpm-backend/src/session.ts
- kpm/kpm-frontend/__test__/__snapshots__/test.spec.tsx.snap
- kpm/kpm-frontend/src/Menu.scss
- kpm/kpm-frontend/src/Menu.tsx
- kpm/kpm-frontend/src/app.tsx
- kpm/kpm-frontend/src/components/icons.tsx
- kpm/kpm-frontend/src/i18n/en.ts
- kpm/kpm-frontend/src/i18n/sv.ts
- kpm/kpm-frontend/src/index.tsx
- kpm/kpm-frontend/src/routes.tsx
- kpm/kpm-frontend/src/state/authState.ts
- kpm/kpm-frontend/src/stylesVars.scss
Indicate if there is unread notifications (in social) on the notifications icon in kpm.
* Implement a widget for showing number of new notifications in frontend.
* Add checking for (social) notifications in backend check session endpoint.
* Call checkValidSession on startup in frontent.
> Indicate notifications

- kpm/kpm-frontend/src/beta/index.html
Also update shortcut icon (the old one was 404).
> Tell devices to handle scaling the sane way.

- kpm/kpm-frontend/src/panes/teaching.tsx
If we have favs in Canvas we should show them, and only them, in the short list.
Fixed hard coded term selection
> Show fav canvas rooms

- kpm/kpm-frontend/__test__/__snapshots__/test-panesGroups.spec.tsx.snap
- kpm/kpm-frontend/__test__/__snapshots__/test-panesProfile.spec.tsx.snap
- kpm/kpm-frontend/__test__/__snapshots__/test-panesServices.spec.tsx.snap
- kpm/kpm-frontend/src/components/groups.scss
- kpm/kpm-frontend/src/components/groups.tsx
- kpm/kpm-frontend/src/components/menu.scss
- kpm/kpm-frontend/src/components/menu.tsx
- kpm/kpm-frontend/src/panes/teaching.scss
> Convert <a> to <button> in back nav

- kpm/kpm-backend/.env.in
- kpm/kpm-backend/src/redisClient.ts
-  change default redis connection timeout
- add ping interval option
> Redis settings

- kpm/kpm-frontend/src/app.scss
- kpm/kpm-frontend/src/components/common.scss
- kpm/kpm-frontend/src/panes/studies.scss
- kpm/kpm-frontend/src/stylesVars.scss
Use kth-style sass variables in stylesVars.scss, to get proper kth-style colors and document where our colours come from.
> Use kth-style colors

- kpm/kpm-frontend/src/stylesReset.scss
intra (or specific page) adds margin to img, which breaks layout.
https://www.kth.se/om/work-at-kth/lediga-jobb/what:job/jobID:603744/where:4/
> Reset margin etc for image.

- kpm/kpm-backend/src/widget.js.ts
This is the CSP fix we discussed. I believe the gzip will remove some of the overhead of the more bloated syntax.
> Don't use innerHTML to inject html for logged out users

- kpm/kpm-backend/src/widget.js.ts
Add the use-personal-menu class to body, to make the canvas (and other) workarounds apply.
https://trello.com/c/qQeyqoHs
> Fix canvas workarounds.

- kpm/kpm-backend-interface/src/index.ts
- kpm/kpm-backend/src/api/teaching.ts
- kpm/kpm-frontend/src/panes/teaching.scss
- kpm/kpm-frontend/src/panes/teaching.tsx
Make courses in teaching starable like programmes and groups.  Also, like programmes and groups, the stars are currently stored in social.  This is good since it makes the stars keep synchronized between the old and the new personal menu until we discontinue the old.
> Star in teaching

- kpm/kpm-frontend/src/panes/studies.tsx
- kpm/kpm-frontend/src/panes/teaching.tsx
- kpm/kpm-frontend/src/stylesReset.scss
So the per-course header has something to head over.
> Use sections for courses.

- kpm/kpm-frontend/__test__/__snapshots__/test-panesProfile.spec.tsx.snap
- kpm/kpm-frontend/src/panes/profile.tsx
New service for managing "my" KTH account.
> Change the change password url.

- kpm/kpm-backend/src/auth.ts
- kpm/kpm-backend/src/widget.js.ts
Set or clear it depending on if the user is logged in or not, on the auth callback and on kpm.js.
> Handle KPM_SSO_START cookie.

- kpm/kpm-frontend/src/panes/studies.tsx
Actually filter the canvas rooms, rather than just showing whatever one happens to first in the json.
> Fix canvas rooms in studies.

- kpm/kpm-frontend/src/panes/teaching.tsx
> Revert "Revert "Links to Startus currently require trailing slash""

- kpm/kpm-backend/src/auth.ts
- kpm/kpm-backend/src/index.ts
- kpm/kpm-frontend/src/Menu.tsx
- kpm/kpm-frontend/src/index.tsx
- kpm/kpm-frontend/src/state/authState.ts
Check with the OpenID Connect server to determine what value to set auth to in kpmLoaded event.
> Check with login server

- kpm/kpm-frontend/__test__/__snapshots__/test.spec.tsx.snap
- kpm/kpm-frontend/src/Menu.tsx
> Fix mobile logout link

- kpm/kpm-backend/__test__/api.spec.ts
- kpm/kpm-backend/__test__/auth.spec.ts
- kpm/kpm-backend/__test__/test.spec.ts
- kpm/kpm-backend/__test__/widget_js.spec.ts
- kpm/kpm-backend/package.json
- kpm/kpm-backend/src/activation.ts
- kpm/kpm-backend/src/api/useBeta.ts
- kpm/kpm-backend/src/auth.ts
- kpm/kpm-backend/src/index.ts
- kpm/kpm-backend/src/widget.js.ts
- package-lock.json
- packages/kpm-api-common/src/errors.ts
So the outer try/catch pattern in Expressjs handlers wasn't implemented. This has now been fixed and simple tests added.
> Improve handling auth errors

- apis/my-canvas-rooms-api/src/api.ts
- apis/my-canvas-rooms-api/src/interface.ts
- kpm/kpm-frontend/src/panes/programme.scss
- kpm/kpm-frontend/src/panes/programme.tsx
This PR is my extended review and continuation of #195 .
Do not merge to master and release until:
* program rooms are published
* students have been enrolled to program rooms
This branch may be merged to #195 before that, though.
> Program rooms improved(?)

- kpm/kpm-backend-interface/src/entities.ts
- kpm/kpm-backend/src/api/studies.ts
- kpm/kpm-frontend/src/components/courseComponents.tsx
- kpm/kpm-frontend/src/components/groups.scss
- kpm/kpm-frontend/src/components/menu.scss
- kpm/kpm-frontend/src/components/menu.tsx
- kpm/kpm-frontend/src/components/menuUtils.ts
- kpm/kpm-frontend/src/i18n/en.ts
- kpm/kpm-frontend/src/i18n/i18n.ts
- kpm/kpm-frontend/src/i18n/sv.ts
- kpm/kpm-frontend/src/panes/studies.scss
- kpm/kpm-frontend/src/panes/studies.tsx
- kpm/kpm-frontend/src/stylesCanvas.scss
- show re-registrations in list of course rounds
- avoid duplicate round header with multiple rounds
- fix round header when no round iexists in course object
> Feature show re-registrations

- kpm/kpm-frontend/src/components/courseComponents.scss
- kpm/kpm-frontend/src/components/courseComponents.tsx
- kpm/kpm-frontend/src/panes/programme.tsx
- kpm/kpm-frontend/src/panes/teaching.tsx
Simplifying exam list and improving layout on desktop and mobile.
> UI exam list

- kpm/kpm-frontend/src/Menu.tsx
Keep the root menu open when navigating to child menu panes.
> Fix mobile root menu behaviour

- kpm/kpm-frontend/__test__/__snapshots__/test-panesGroups.spec.tsx.snap
- kpm/kpm-frontend/__test__/__snapshots__/test-panesProfile.spec.tsx.snap
- kpm/kpm-frontend/__test__/__snapshots__/test-panesServices.spec.tsx.snap
- kpm/kpm-frontend/__test__/__snapshots__/test.spec.tsx.snap
- kpm/kpm-frontend/src/Menu.tsx
- kpm/kpm-frontend/src/components/groupsUtils.ts
- kpm/kpm-frontend/src/components/menu.tsx
- kpm/kpm-frontend/src/components/menuUtils.ts
This only supports tabbing. We don't support:
- key nav in menu pane
- ~~esc to close~~ (FIXED in [c086b5c](https://github.com/KTH/kpm/pull/209/commits/c086b5c47fd438eb9d6f6cd838f808fb91e00ee0))
> Trap focus within menu pane when tabbing

- kpm/kpm-frontend/src/Menu.scss
Make sure root menu stays white during navigation
Remove blue outline artifact when navigating back to root menu
> UI fix mobile menu

- kpm/kpm-frontend/src/stylesCanvas.scss
Ref: https://edge.sys.kth.se/itsm/EfecteFrameset.do#/workspace/datacard/view/192316185
> Hotfix KTH-INC-4459133 Tooltip blocks tripple-dot button in mailbox

- kpm/kpm-backend/src/api/studies.ts
This PR adds extra logic to limit the amount of courses considered "current"
> Restrict current studies to antagna

- kpm/kpm-backend/src/widget.js/loggedIn.js
- kpm/kpm-backend/src/widget.js/notLoggedIn.js
- kpm/kpm-frontend/src/beta/index.html
- kpm/kpm-frontend/src/beta/index.scss
- kpm/kpm-frontend/src/stylesCanvas.scss
This PR means that developers can choose two ways of importing `kpm.js`:
1. kpm.js in a page WITH `<div class="kth-kpm">` (somewhere in the body)
In this "mode", the script will inject kpm in the `kth-kpm` container. The script will not do modifications outside the container: will not add extra styles to the body nor create nodes
2. kpm.js in a page WITHOUT `<div class="kth-kpm">`
In this "mode", the script will inject kpm in the body. The script decides where to add kpm _and_ will also modify body styles
> Add modifications to DOM conditionally

- kpm/kpm-backend/src/widget.js/loggedIn.js
- kpm/kpm-backend/src/widget.js/notLoggedIn.js
- kpm/kpm-frontend/src/index.tsx
This PR checks if the current document is an iframe in the beginning of all. That means no React, no CSS is loaded in that case
> Prevent kpm to do anything when loaded inside <iframe>
